import type { PageContent } from "../types";

interface EnService {
  slug: string;
  eyebrow: string;
  title: string;
  sub: string;
  stats: { value: string; label: string }[];
  included: { title: string; body: string }[];
  process: { title: string; body: string }[];
  tech: string[];
  deliverables: { title: string; body: string }[];
  ctaTitle: string;
  ctaBody: string;
}

function build(s: EnService): PageContent {
  return {
    title: `${s.title} | En'nobler`,
    sections: [
      {
        type: "hero",
        eyebrow: s.eyebrow,
        title: s.title,
        subtitle: s.sub,
        primaryCta: { label: "Start a Project", to: "/contact" },
        secondaryCta: { label: "See What's Included", to: "#features" },
        chips: ["Discover", "Build", "Test", "Ship"],
      },
      { type: "stats", items: s.stats },
      {
        type: "features",
        anchor: "features",
        eyebrow: "What's included",
        title: "Everything in this service",
        subtitle: "A focused set of capabilities delivered end-to-end — no gaps, no handoffs to unknown parties.",
        columns: 3,
        numbered: true,
        items: s.included,
      },
      {
        type: "steps",
        anchor: "process",
        eyebrow: "How it works",
        title: "Our delivery process",
        items: s.process,
      },
      {
        type: "tags",
        anchor: "tech",
        eyebrow: "Tools & technologies",
        title: "What we work with",
        subtitle: "We use the right tool for the job — not the trendiest one.",
        items: s.tech,
      },
      {
        type: "features",
        anchor: "deliverables",
        eyebrow: "What you get",
        title: "Deliverables",
        columns: 2,
        numbered: true,
        dark: true,
        items: s.deliverables,
      },
      {
        type: "cta",
        eyebrow: "Let's work together",
        title: s.ctaTitle,
        body: s.ctaBody,
        cta: { label: "Get Started", to: "/contact" },
      },
    ],
  };
}

const DATA: EnService[] = [
  {
    slug: "software-development",
    eyebrow: "Services / Custom Software Development",
    title: "Software built exactly for your business.",
    sub: "We design and build custom software from scratch — tailored to your workflows, integrated with your systems, and engineered to scale.",
    stats: [
      { value: "50+", label: "projects shipped" },
      { value: "4.9★", label: "client satisfaction" },
      { value: "< 2 wks", label: "to first sprint" },
    ],
    included: [
      { title: "Requirements & Architecture", body: "We map your business logic, data flows, and system boundaries before writing a single line of code." },
      { title: "Full-Stack Engineering", body: "Frontend, backend, database — all built in-house by a single cohesive team with no outsourcing." },
      { title: "API-First Design", body: "Every module is built with clean APIs so integrations and future extensions are straightforward." },
      { title: "Code Quality & Reviews", body: "Peer-reviewed code, linting, automated tests, and CI checks at every pull request." },
      { title: "DevOps & Deployment", body: "We set up your CI/CD pipelines and deploy to your cloud environment of choice." },
      { title: "Ongoing Support", body: "Post-launch bug fixes, performance monitoring, and incremental feature development." },
    ],
    process: [
      { title: "Discovery", body: "Understand business goals, users, and constraints." },
      { title: "Architecture", body: "Define tech stack, data models, and system design." },
      { title: "Build", body: "Iterative sprints with demos every two weeks." },
      { title: "QA & UAT", body: "Automated tests plus user acceptance testing." },
      { title: "Launch", body: "Deploy, monitor, and hand over documentation." },
    ],
    tech: ["Python", "Node.js", "React", "TypeScript", "PostgreSQL", "MongoDB", "Redis", "Docker", "GitHub Actions", "AWS", "REST APIs", "GraphQL"],
    deliverables: [
      { title: "Source Code Repository", body: "Full codebase with commit history, branching strategy, and README documentation." },
      { title: "Architecture Diagram", body: "System design doc covering all components, integrations, and data flows." },
      { title: "API Documentation", body: "Complete API reference — endpoints, payloads, auth, and error handling." },
      { title: "Test Suite", body: "Unit, integration, and end-to-end test coverage for all core functionality." },
      { title: "Deployment Pipeline", body: "CI/CD configuration for staging and production environments." },
      { title: "Maintenance Handover", body: "Runbook, environment setup guide, and 30-day post-launch support." },
    ],
    ctaTitle: "Ready to build your custom solution?",
    ctaBody: "Tell us what you need — we'll scope it, architect it, and ship it. No fluff, no vendor lock-in.",
  },
  {
    slug: "web-platform-development",
    eyebrow: "Services / Web & Platform Development",
    title: "Fast, scalable web platforms that perform.",
    sub: "From marketing sites to complex SaaS platforms — we build web products that load fast, rank well, and convert visitors into customers.",
    stats: [
      { value: "40+", label: "platforms launched" },
      { value: "< 1s", label: "avg load time target" },
      { value: "100%", label: "mobile responsive" },
    ],
    included: [
      { title: "UX-Driven Frontend", body: "Pixel-perfect, accessible interfaces built with modern frameworks — fast by default." },
      { title: "CMS Integration", body: "Headless CMS setup so your team can update content without touching code." },
      { title: "Performance Optimization", body: "Core Web Vitals tuning, lazy loading, CDN setup, and image optimization." },
      { title: "SEO Architecture", body: "Semantic HTML, meta strategy, sitemap, and structured data from day one." },
      { title: "Authentication & Multi-tenancy", body: "Role-based access, SSO, and multi-tenant architecture for SaaS products." },
      { title: "Analytics & Tracking", body: "GA4, Mixpanel, or custom event tracking — wired in and tested before launch." },
    ],
    process: [
      { title: "Audit & Plan", body: "Review existing site or define new platform requirements." },
      { title: "Design", body: "Wireframes and component library sign-off." },
      { title: "Development", body: "Component-driven build with weekly demos." },
      { title: "Optimise", body: "Performance audit and Core Web Vitals fixes." },
      { title: "Launch", body: "Go-live with monitoring and 14-day hypercare." },
    ],
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Sanity CMS", "Contentful", "Vercel", "Cloudflare", "PostgreSQL", "Supabase", "Stripe", "GA4"],
    deliverables: [
      { title: "Production Web App", body: "Fully deployed, optimised web platform on your domain." },
      { title: "CMS Configuration", body: "Content model, editorial workflow, and training guide for your team." },
      { title: "SEO Baseline Report", body: "Initial rankings snapshot plus on-page SEO audit." },
      { title: "Performance Report", body: "Lighthouse scores and Core Web Vitals baseline." },
      { title: "Component Library", body: "Documented UI component library for future development." },
      { title: "Analytics Dashboard", body: "Configured tracking with key conversion events." },
    ],
    ctaTitle: "Let's build your next web platform.",
    ctaBody: "Whether it's a relaunch, a new SaaS, or a high-traffic marketing site — we scope and ship.",
  },
  {
    slug: "mobile-app-development",
    eyebrow: "Services / Mobile App Development",
    title: "Mobile apps users actually keep on their phones.",
    sub: "iOS, Android, and cross-platform apps — built for performance, offline resilience, and app store approval from the first submission.",
    stats: [
      { value: "30+", label: "apps shipped" },
      { value: "4.8★", label: "avg app store rating" },
      { value: "95%", label: "first-submission approval" },
    ],
    included: [
      { title: "iOS & Android Native", body: "Swift and Kotlin for performance-critical apps where native UX matters." },
      { title: "Cross-Platform (React Native)", body: "Single codebase for both platforms — faster delivery, lower cost, same quality feel." },
      { title: "Offline-First Architecture", body: "Local data sync, background jobs, and conflict resolution for apps that work without internet." },
      { title: "Push Notifications", body: "Targeted, scheduled, and behaviour-triggered notifications that drive retention." },
      { title: "App Store Optimisation", body: "Screenshots, descriptions, and metadata crafted for maximum visibility and conversion." },
      { title: "Analytics & Crash Reporting", body: "Mixpanel, Firebase, or Sentry wired in so you know exactly what users do." },
    ],
    process: [
      { title: "Scoping", body: "Define user journeys, platform targets, and MVP feature set." },
      { title: "UX Design", body: "Figma prototypes reviewed and approved before code starts." },
      { title: "Development", body: "Two-week sprints with TestFlight/Play Console builds." },
      { title: "Testing", body: "Device lab testing across iOS and Android versions." },
      { title: "Store Launch", body: "Submission, review, and post-launch monitoring." },
    ],
    tech: ["React Native", "Swift", "Kotlin", "Expo", "Firebase", "Supabase", "Redux", "Zustand", "Fastlane", "TestFlight", "Play Console", "Sentry"],
    deliverables: [
      { title: "App Store & Play Store Listing", body: "Published app with optimised screenshots, descriptions, and metadata." },
      { title: "Source Code", body: "Full codebase with CI/CD pipeline for ongoing builds." },
      { title: "Backend API", body: "Documented REST or GraphQL API powering the app." },
      { title: "Analytics Setup", body: "Event tracking, funnels, and crash reporting configured." },
      { title: "Test Coverage Report", body: "Unit and integration test results with device matrix." },
      { title: "Release Runbook", body: "Step-by-step guide for future releases and hotfixes." },
    ],
    ctaTitle: "Got a mobile app idea?",
    ctaBody: "We'll take it from wireframe to app store — on time and without the usual resubmission drama.",
  },
  {
    slug: "ui-ux-design",
    eyebrow: "Services / UI/UX & Product Design",
    title: "Design that makes complex things feel simple.",
    sub: "User research, information architecture, wireframes, and high-fidelity prototypes — so your product ships with a clear, tested experience.",
    stats: [
      { value: "25+", label: "products designed" },
      { value: "3×", label: "avg conversion uplift" },
      { value: "100%", label: "handoff-ready Figma" },
    ],
    included: [
      { title: "User Research", body: "Interviews, surveys, and usability tests to understand what users actually need." },
      { title: "Information Architecture", body: "Sitemaps, user flows, and navigation structures before any visuals are drawn." },
      { title: "Wireframing", body: "Low-fidelity layouts that map out every screen and interaction state." },
      { title: "High-Fidelity UI Design", body: "Polished Figma designs with typography, colour, spacing, and component states." },
      { title: "Prototyping & Testing", body: "Clickable prototypes tested with real users before development starts." },
      { title: "Design System", body: "Reusable component library with documented tokens for consistent scaling." },
    ],
    process: [
      { title: "Research", body: "User interviews and competitor audit." },
      { title: "IA & Flows", body: "Sitemaps, task flows, and wireframes." },
      { title: "Visual Design", body: "High-fidelity screens and component design." },
      { title: "Prototype & Test", body: "Usability testing with target users." },
      { title: "Handoff", body: "Dev-ready Figma with specs and assets." },
    ],
    tech: ["Figma", "FigJam", "Maze", "Hotjar", "Miro", "Zeroheight", "Storybook", "Lottie", "Principle", "UserTesting"],
    deliverables: [
      { title: "Research Report", body: "User interview synthesis, personas, and key insight summary." },
      { title: "User Flow Diagrams", body: "End-to-end task flows for all primary user journeys." },
      { title: "Wireframe Deck", body: "Full low-fidelity layout for every screen." },
      { title: "High-Fidelity Designs", body: "Production-ready Figma files with all states and variants." },
      { title: "Clickable Prototype", body: "Shareable prototype for stakeholder review and usability testing." },
      { title: "Design System", body: "Component library with documented colour, type, spacing, and icon tokens." },
    ],
    ctaTitle: "Want users to love your product?",
    ctaBody: "Good engineering deserves good design. We close the gap between what you build and what users want.",
  },
  {
    slug: "cloud-devops",
    eyebrow: "Services / Cloud & DevOps Solutions",
    title: "Infrastructure that ships faster and breaks less.",
    sub: "Cloud architecture, CI/CD automation, containerisation, and monitoring — so your team can deploy with confidence every single day.",
    stats: [
      { value: "99.9%", label: "uptime SLA target" },
      { value: "10×", label: "faster deployments" },
      { value: "Zero", label: "manual release steps" },
    ],
    included: [
      { title: "Cloud Architecture", body: "Right-sized AWS, GCP, or Azure infrastructure — no over-provisioning, no single points of failure." },
      { title: "CI/CD Pipelines", body: "Automated build, test, and deploy pipelines from commit to production." },
      { title: "Containerisation", body: "Docker and Kubernetes setup for consistent, portable, scalable workloads." },
      { title: "Infrastructure as Code", body: "Terraform or Pulumi so your infra is version-controlled and repeatable." },
      { title: "Monitoring & Alerting", body: "Datadog, Grafana, or CloudWatch dashboards with on-call alerting." },
      { title: "Cost Optimisation", body: "Reserved instances, spot fleets, and resource right-sizing to cut cloud bills." },
    ],
    process: [
      { title: "Audit", body: "Review existing infra, bottlenecks, and security posture." },
      { title: "Design", body: "Define target architecture, pipeline stages, and SLAs." },
      { title: "Build", body: "Provision infra with IaC and configure pipelines." },
      { title: "Migrate", body: "Zero-downtime cutover from old to new environment." },
      { title: "Monitor", body: "Dashboards, runbooks, and ongoing cost reviews." },
    ],
    tech: ["AWS", "GCP", "Azure", "Terraform", "Pulumi", "Docker", "Kubernetes", "Helm", "GitHub Actions", "GitLab CI", "Datadog", "Grafana", "Prometheus", "ArgoCD"],
    deliverables: [
      { title: "Infrastructure as Code", body: "Terraform/Pulumi codebase for all provisioned resources." },
      { title: "CI/CD Pipeline", body: "Fully automated build, test, and deploy workflow." },
      { title: "Architecture Diagram", body: "Current-state and target-state infra diagrams." },
      { title: "Runbook", body: "Incident response, rollback procedures, and scaling playbooks." },
      { title: "Monitoring Dashboard", body: "Live dashboards covering latency, error rates, and cost." },
      { title: "Security Baseline Report", body: "IAM audit, secrets management review, and CVE scan results." },
    ],
    ctaTitle: "Time to stop babysitting your servers?",
    ctaBody: "We'll automate your deployments, harden your infrastructure, and let your team focus on shipping features.",
  },
  {
    slug: "api-development",
    eyebrow: "Services / API Development & Integrations",
    title: "APIs that connect your systems reliably.",
    sub: "Secure, well-documented REST and GraphQL APIs — plus third-party integrations that keep your products, tools, and data in sync.",
    stats: [
      { value: "< 100ms", label: "avg API response" },
      { value: "99.95%", label: "uptime target" },
      { value: "100%", label: "documented endpoints" },
    ],
    included: [
      { title: "REST API Design", body: "Resource-based API design following OpenAPI 3.0 spec with versioning from day one." },
      { title: "GraphQL APIs", body: "Flexible, query-efficient APIs for products with complex, varied data requirements." },
      { title: "Third-Party Integrations", body: "Stripe, Salesforce, HubSpot, Twilio, Xero, or any REST/webhook-based service." },
      { title: "Authentication & Security", body: "OAuth 2.0, JWT, API key management, rate limiting, and input validation." },
      { title: "Webhooks & Event Streams", body: "Outbound webhooks and event-driven integrations for real-time data flows." },
      { title: "API Testing & Monitoring", body: "Automated contract tests, load tests, and uptime monitoring in production." },
    ],
    process: [
      { title: "Requirements", body: "Map data flows, consumers, and integration points." },
      { title: "Contract Design", body: "OpenAPI spec reviewed and agreed before coding." },
      { title: "Development", body: "Build endpoints with tests at each stage." },
      { title: "Integration", body: "Connect and test with all consuming systems." },
      { title: "Documentation", body: "Publish developer docs and Postman collection." },
    ],
    tech: ["Node.js", "Python", "FastAPI", "Express", "GraphQL", "REST", "OpenAPI 3.0", "Postman", "OAuth 2.0", "JWT", "Redis", "RabbitMQ", "Kafka", "Webhooks"],
    deliverables: [
      { title: "OpenAPI Specification", body: "Machine-readable API spec for all endpoints, payloads, and auth flows." },
      { title: "Developer Documentation", body: "Hosted docs with examples, error codes, and quick-start guide." },
      { title: "Postman Collection", body: "Ready-to-run collection for every endpoint." },
      { title: "Test Suite", body: "Automated contract, integration, and load tests." },
      { title: "Monitoring Setup", body: "Uptime and latency monitoring with alerting." },
      { title: "Integration Guide", body: "Step-by-step guide for each third-party connection." },
    ],
    ctaTitle: "Need your systems to talk to each other?",
    ctaBody: "We design and build APIs that are secure, fast, and a pleasure for developers to work with.",
  },
  {
    slug: "ai-automation",
    eyebrow: "Services / AI & Automation Solutions",
    title: "Automate the work. Amplify the team.",
    sub: "Custom AI models, LLM integrations, and intelligent workflow automation — built to reduce manual effort and surface insights that drive decisions.",
    stats: [
      { value: "60%", label: "avg manual effort cut" },
      { value: "3×", label: "faster data processing" },
      { value: "GPT-4 + Claude", label: "LLM expertise" },
    ],
    included: [
      { title: "LLM Integration", body: "Embed GPT-4, Claude, or Gemini into your products — with prompt engineering and context management done right." },
      { title: "AI-Aided Engineering", body: "Copilot tooling, code review bots, and AI-assisted QA wired into your dev workflow." },
      { title: "Process Automation", body: "Replace repetitive manual tasks with robust, auditable automated workflows." },
      { title: "Document Intelligence", body: "Extract, classify, and summarise data from PDFs, emails, and scanned documents." },
      { title: "ML Model Development", body: "Custom classification, prediction, and recommendation models trained on your data." },
      { title: "RAG & Knowledge Bases", body: "Retrieval-augmented generation pipelines so your AI answers questions from your own data." },
    ],
    process: [
      { title: "Discovery", body: "Map manual processes and identify automation ROI." },
      { title: "Data Audit", body: "Assess data quality, availability, and sensitivity." },
      { title: "Prototype", body: "Build and validate a working proof of concept." },
      { title: "Build", body: "Production-grade pipeline with logging and fallbacks." },
      { title: "Monitor", body: "Accuracy tracking, drift detection, and retraining triggers." },
    ],
    tech: ["Python", "LangChain", "LlamaIndex", "OpenAI API", "Anthropic Claude", "Hugging Face", "Pinecone", "Weaviate", "Airflow", "n8n", "FastAPI", "Celery", "PostgreSQL", "S3"],
    deliverables: [
      { title: "Automation Workflow", body: "End-to-end automated process with logging, error handling, and audit trail." },
      { title: "AI Integration", body: "LLM-powered feature embedded in your product or internal tool." },
      { title: "ML Model + API", body: "Trained model served as an API with versioning and rollback." },
      { title: "Evaluation Report", body: "Accuracy benchmarks, failure analysis, and improvement roadmap." },
      { title: "Monitoring Dashboard", body: "Live metrics on automation performance and model drift." },
      { title: "Retraining Playbook", body: "Guide for updating models as your data evolves." },
    ],
    ctaTitle: "Ready to put AI to work?",
    ctaBody: "We cut through the hype and build automation that actually sticks — practical, auditable, and ROI-positive.",
  },
  {
    slug: "quality-assurance",
    eyebrow: "Services / Software Quality Assurance",
    title: "Bugs caught before your users find them.",
    sub: "Manual and automated testing across web, mobile, and APIs — so every release ships with confidence, not crossed fingers.",
    stats: [
      { value: "98%", label: "defect detection rate" },
      { value: "5×", label: "faster regression cycles" },
      { value: "Zero", label: "critical bugs in prod (target)" },
    ],
    included: [
      { title: "Manual Exploratory Testing", body: "Skilled QA engineers who think like users — finding edge cases automated scripts miss." },
      { title: "Test Automation", body: "Selenium, Playwright, or Cypress suites that run on every PR and block bad merges." },
      { title: "API Testing", body: "Contract and load testing for every endpoint with Postman, k6, or custom scripts." },
      { title: "Mobile QA", body: "Real-device testing across iOS and Android versions, screen sizes, and network conditions." },
      { title: "Performance Testing", body: "Load, stress, and soak tests to find bottlenecks before go-live." },
      { title: "Security Testing", body: "OWASP Top 10 checks, penetration testing basics, and dependency CVE scanning." },
    ],
    process: [
      { title: "Test Planning", body: "Review requirements and define test scope, types, and exit criteria." },
      { title: "Test Design", body: "Write test cases, scripts, and automation framework setup." },
      { title: "Execution", body: "Run manual and automated tests; log and triage defects." },
      { title: "Regression", body: "Full regression suite on every release candidate." },
      { title: "Sign-off", body: "Test summary report and formal UAT sign-off." },
    ],
    tech: ["Playwright", "Cypress", "Selenium", "Postman", "k6", "JMeter", "Appium", "TestRail", "Jira", "BrowserStack", "Sentry", "OWASP ZAP"],
    deliverables: [
      { title: "Test Plan", body: "Scope, strategy, resource allocation, and exit criteria." },
      { title: "Test Case Library", body: "Full suite of manual and automated test cases in TestRail or equivalent." },
      { title: "Automation Suite", body: "CI-integrated automated test scripts with coverage report." },
      { title: "Defect Reports", body: "Logged, prioritised, and tracked defect list with root cause analysis." },
      { title: "Performance Report", body: "Load test results with bottleneck identification and recommendations." },
      { title: "Test Summary Report", body: "Release sign-off document with pass/fail rates and residual risk." },
    ],
    ctaTitle: "Shipping without QA is just beta testing in production.",
    ctaBody: "Let us catch the bugs before your users do — with testing that fits your release cadence.",
  },
  {
    slug: "ecommerce-solutions",
    eyebrow: "Services / E-Commerce Solutions",
    title: "Online stores built to convert and scale.",
    sub: "Custom storefronts, seamless checkout, and robust backend systems — from D2C brands to complex multi-vendor marketplaces.",
    stats: [
      { value: "20+", label: "stores launched" },
      { value: "+35%", label: "avg conversion uplift" },
      { value: "Multi-vendor", label: "marketplace capable" },
    ],
    included: [
      { title: "Custom Storefront", body: "Tailored, brand-led shopping experiences — not template-constrained Shopify themes." },
      { title: "Payment Gateways", body: "Stripe, PayHere, PayPal, and local payment methods integrated and tested." },
      { title: "Inventory Management", body: "Real-time stock tracking, low-stock alerts, and multi-warehouse support." },
      { title: "Order Management System", body: "End-to-end order lifecycle — placed, packed, shipped, returned — with status tracking." },
      { title: "Multi-Vendor Marketplace", body: "Vendor onboarding, commission management, and split payments for marketplace models." },
      { title: "Search & Recommendations", body: "Fast faceted search and AI-powered product recommendations to increase basket size." },
    ],
    process: [
      { title: "Discovery", body: "Map buyer journeys, product catalogue, and fulfilment workflows." },
      { title: "UX Design", body: "Storefront and checkout designed for maximum conversion." },
      { title: "Development", body: "Platform build with all integrations wired and tested." },
      { title: "Data Migration", body: "Product, customer, and order data migrated from existing platform." },
      { title: "Launch", body: "Go-live with payment testing, load testing, and support cover." },
    ],
    tech: ["Next.js", "React", "Node.js", "Stripe", "PayHere", "Shopify API", "WooCommerce", "Medusa.js", "Elasticsearch", "PostgreSQL", "Redis", "AWS S3", "Cloudflare"],
    deliverables: [
      { title: "Production Storefront", body: "Fully deployed, branded e-commerce site with all pages and flows." },
      { title: "Payment Integration", body: "Tested payment flow with sandbox and production credentials." },
      { title: "Admin Dashboard", body: "Order, inventory, and customer management interface." },
      { title: "Search & Filter", body: "Faceted product search with category, price, and attribute filters." },
      { title: "Analytics Setup", body: "Purchase funnel tracking, revenue events, and abandoned cart monitoring." },
      { title: "Launch Checklist", body: "Performance audit, security review, and load test results." },
    ],
    ctaTitle: "Ready to sell online properly?",
    ctaBody: "We build stores that look great, load fast, and turn browsers into buyers — without the platform lock-in.",
  },
  {
    slug: "digital-transformation",
    eyebrow: "Services / IT Consulting & Digital Transformation",
    title: "Technology strategy that moves the business forward.",
    sub: "Hands-on consulting to modernise legacy systems, align your tech stack with business goals, and build the internal capability to sustain growth.",
    stats: [
      { value: "15+", label: "transformations led" },
      { value: "30%", label: "avg infra cost reduction" },
      { value: "6 weeks", label: "to actionable roadmap" },
    ],
    included: [
      { title: "Technology Audit", body: "A clear-eyed review of your current stack — what works, what doesn't, and what's holding you back." },
      { title: "Roadmap Planning", body: "Prioritised, costed transformation roadmap aligned to your business timeline." },
      { title: "Legacy Modernisation", body: "Strangler fig, re-platform, or greenfield — the right migration approach for your risk tolerance." },
      { title: "Vendor Selection", body: "Unbiased evaluation of platforms, tools, and partners so you choose with confidence." },
      { title: "Team Advisory", body: "Fractional CTO support, architecture reviews, and developer mentoring." },
      { title: "Change Management", body: "Stakeholder alignment, training plans, and adoption metrics so the change actually sticks." },
    ],
    process: [
      { title: "Discovery", body: "Stakeholder interviews and technical audit." },
      { title: "Assessment", body: "Gap analysis and risk register." },
      { title: "Roadmap", body: "Prioritised initiative list with effort/impact scores." },
      { title: "Pilot", body: "Low-risk first initiative to validate approach." },
      { title: "Scale", body: "Roll out transformation across systems and teams." },
    ],
    tech: ["Architecture Review", "Cloud Strategy", "Legacy Assessment", "Agile Transformation", "DevOps Maturity", "API Strategy", "Data Platform Design", "Vendor RFP", "Team Structuring"],
    deliverables: [
      { title: "Technology Audit Report", body: "Current-state analysis with findings, risks, and quick wins." },
      { title: "Transformation Roadmap", body: "12–24 month initiative plan with owners, timelines, and success metrics." },
      { title: "Architecture Decision Records", body: "Documented rationale for major technical decisions." },
      { title: "Vendor Evaluation Matrix", body: "Scored comparison of shortlisted platforms or tools." },
      { title: "Team Capability Assessment", body: "Skills gap analysis and hiring/training recommendations." },
      { title: "Executive Summary Deck", body: "Board-ready presentation of findings and recommended direction." },
    ],
    ctaTitle: "Need clarity on your tech direction?",
    ctaBody: "We give you an honest view of where you are, a practical plan for where to go, and the hands-on support to get there.",
  },
];

export const ennoblerServiceDetails: Record<string, PageContent> = Object.fromEntries(
  DATA.map((d) => [d.slug, build(d)]),
);
